# Generated by Django 4.0.2 on 2022-03-26 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='trans_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('des1', models.CharField(max_length=100)),
                ('des2', models.CharField(max_length=150)),
                ('tr_amount', models.FloatField(max_length=15)),
                ('in_out', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
