# Generated by Django 4.0.2 on 2022-04-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_key_pair2_key_pair1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_pair1',
            name='private_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='key_pair1',
            name='public_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='key_pair2',
            name='private_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='key_pair2',
            name='public_key',
            field=models.IntegerField(default=0),
        ),
    ]
