# Generated by Django 4.0.2 on 2022-04-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='amount',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
