# Generated by Django 4.0.2 on 2022-04-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_notification_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
